Update build-multiplatform.yml

diff --git a/.github/workflows/build-multiplatform.yml b/.github/workflows/build-multiplatform.yml
--- a/.github/workflows/build-multiplatform.yml
+++ b/.github/workflows/build-multiplatform.yml
@@ -77,9 +77,9 @@ jobs:
                 \${cksumAlg} - a <<<\"\${val}\"; \
                 \${cksumAlg} - 'A[1]' <<<\"\${val}\"; \
                 \${cksumAlg} - 'AA[foo]' <<<\"\${val}\"; \
-                for nn in \"\${a}\" \"\${A[1]}\" \"\${AA[foo]}\"; do \
-                  [[ \"\${a0}\" == \"\${nn}\" ]] || echo \"::warning title=timep.so (${{ matrix.arch }}) ${cksumAlg} bind-to-variable test failed::One of the bind-to-variable tests for the \${cksumAlg} loadable for arch=${{ matrix.arch }} timep.so failed! Please investigate.\"; \
-                done; \
+                [[ \"\${a0}\" == \"\${a}\" ]] || echo \"::warning title=timep.so (${{ matrix.arch }}) ${cksumAlg} - the 'bind to standard variable' test failed::One of the bind-to-variable tests for the \${cksumAlg} loadable for arch=${{ matrix.arch }} timep.so failed! Please investigate.\"; \
+                [[ \"\${a0}\" == \"\${A[1]}\" ]] || echo \"::warning title=timep.so (${{ matrix.arch }}) ${cksumAlg} - the 'bind to indexed array' test failed::One of the bind-to-variable tests for the \${cksumAlg} loadable for arch=${{ matrix.arch }} timep.so failed! Please investigate.\"; \
+                [[ \"\${a0}\" == \"\${AA[foo]}\" ]] || echo \"::warning title=timep.so (${{ matrix.arch }}) ${cksumAlg} - the 'bind to associative array' test failed::One of the bind-to-variable tests for the \${cksumAlg} loadable for arch=${{ matrix.arch }} timep.so failed! Please investigate.\"; \
               done; 
               "
             
